<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class FarmerSeeder extends Seeder
{
    /**
     * Seed the farmers table with sample data.
     */
    public function run(): void
    {
        // 👈 1. Turn off foreign key constraints
        Schema::disableForeignKeyConstraints();

        DB::table('farmers')->truncate();

        // 👈 2. Turn the safety lock back on
        Schema::enableForeignKeyConstraints();

        DB::table('farmers')->insert([
            // Farmer 1: Juan Dela Cruz
            [
                'id' => '11111111-1111-1111-1111-111111111111',
                'rsbsa_no' => '2026-001-FARMER',
                'transaction_code' => 'TRX-001',
                'photo_path' => null,
                'surname' => 'Dela Cruz',
                'first_name' => 'Juan',
                'middle_name' => 'Santos',
                'ext_name' => null,
                'no_middle_name' => false,
                'no_ext_name' => true,
                'sex' => 'Male',
                'permanent_house_no' => '123',
                'permanent_street' => 'Main Street',
                'permanent_brgy' => 'Poblacion',
                'permanent_city' => 'Santa Rosa',
                'permanent_province' => 'Laguna',
                'permanent_region' => 'CALABARZON',
                'provincial_house_no' => null,
                'provincial_street' => null,
                'provincial_brgy' => null,
                'provincial_city' => null,
                'provincial_province' => null,
                'provincial_region' => null,
                'birthdate' => Carbon::create(1975, 5, 15),
                'place_of_birth_city' => 'Santa Rosa',
                'place_of_birth_province' => 'Laguna',
                'mobile_number' => '09171234567',
                'is_mobile_owner' => true,
                'mobile_owner_first_name' => null,
                'mobile_owner_middle_name' => null,
                'mobile_owner_surname' => null,
                'mobile_owner_ext_name' => null,
                'mothers_maiden_first_name' => 'Maria',
                'mothers_maiden_middle_name' => 'Reyes',
                'mothers_maiden_surname' => 'Lopez',
                'mothers_maiden_ext_name' => null,
                'civil_status' => 'Married',
                'spouse_first_name' => 'Rosa',
                'spouse_middle_name' => 'Gonzales',
                'spouse_surname' => 'Dela Cruz',
                'spouse_ext_name' => null,
                'highest_education' => 'High School non K-12',
                'religion' => 'Roman Catholic',
                'id_type' => 'GSIS ID',
                'id_number' => '123456789',
                'is_icc_ip' => false,
                'icc_ip_name' => null,
                'is_pwd' => false,
                'is_4ps_beneficiary' => false,
                'association_1' => 'Farmers Cooperative Alpha',
                'association_2' => null,
                'association_3' => null,
                'livelihood_type' => 'Farmer',
                'qr_code_hash' => hash('sha256', 'farmer_juan_001'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Farmer 2: Maria Garcia
            [
                'id' => '22222222-2222-2222-2222-222222222222',
                'rsbsa_no' => '2026-002-FARMER',
                'transaction_code' => 'TRX-002',
                'photo_path' => null,
                'surname' => 'Garcia',
                'first_name' => 'Maria',
                'middle_name' => 'Fernandez',
                'ext_name' => null,
                'no_middle_name' => false,
                'no_ext_name' => true,
                'sex' => 'Female',
                'permanent_house_no' => '456',
                'permanent_street' => 'Rizal Avenue',
                'permanent_brgy' => 'Bambang',
                'permanent_city' => 'Antipolo',
                'permanent_province' => 'Rizal',
                'permanent_region' => 'CALABARZON',
                'provincial_house_no' => null,
                'provincial_street' => null,
                'provincial_brgy' => null,
                'provincial_city' => null,
                'provincial_province' => null,
                'provincial_region' => null,
                'birthdate' => Carbon::create(1982, 3, 22),
                'place_of_birth_city' => 'Antipolo',
                'place_of_birth_province' => 'Rizal',
                'mobile_number' => '09187654321',
                'is_mobile_owner' => true,
                'mobile_owner_first_name' => null,
                'mobile_owner_middle_name' => null,
                'mobile_owner_surname' => null,
                'mobile_owner_ext_name' => null,
                'mothers_maiden_first_name' => 'Ana',
                'mothers_maiden_middle_name' => 'Santos',
                'mothers_maiden_surname' => 'Reyes',
                'mothers_maiden_ext_name' => null,
                'civil_status' => 'Single',
                'spouse_first_name' => null,
                'spouse_middle_name' => null,
                'spouse_surname' => null,
                'spouse_ext_name' => null,
                'highest_education' => 'College',
                'religion' => 'Roman Catholic',
                'id_type' => 'Drivers License',
                'id_number' => '987654321',
                'is_icc_ip' => false,
                'icc_ip_name' => null,
                'is_pwd' => false,
                'is_4ps_beneficiary' => true,
                'association_1' => 'Womens Farmers Network',
                'association_2' => 'Eco Farming Group',
                'association_3' => null,
                'livelihood_type' => 'Farmer',
                'qr_code_hash' => hash('sha256', 'farmer_maria_002'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Farmer 3: Pedro Santos
            [
                'id' => '33333333-3333-3333-3333-333333333333',
                'rsbsa_no' => '2026-003-FARMER',
                'transaction_code' => 'TRX-003',
                'photo_path' => null,
                'surname' => 'Santos',
                'first_name' => 'Pedro',
                'middle_name' => 'Villanueva',
                'ext_name' => 'Jr.',
                'no_middle_name' => false,
                'no_ext_name' => false,
                'sex' => 'Male',
                'permanent_house_no' => '789',
                'permanent_street' => 'Aguinaldo Street',
                'permanent_brgy' => 'San Isidro',
                'permanent_city' => 'Cabuyao',
                'permanent_province' => 'Laguna',
                'permanent_region' => 'CALABARZON',
                'provincial_house_no' => null,
                'provincial_street' => null,
                'provincial_brgy' => null,
                'provincial_city' => null,
                'provincial_province' => null,
                'provincial_region' => null,
                'birthdate' => Carbon::create(1968, 7, 10),
                'place_of_birth_city' => 'Cabuyao',
                'place_of_birth_province' => 'Laguna',
                'mobile_number' => '09098765432',
                'is_mobile_owner' => false,
                'mobile_owner_first_name' => 'Ramon',
                'mobile_owner_middle_name' => 'Cruz',
                'mobile_owner_surname' => 'Santos',
                'mobile_owner_ext_name' => null,
                'mothers_maiden_first_name' => 'Corazon',
                'mothers_maiden_middle_name' => 'Villanueva',
                'mothers_maiden_surname' => 'Villanueva',
                'mothers_maiden_ext_name' => null,
                'civil_status' => 'Married',
                'spouse_first_name' => 'Josefina',
                'spouse_middle_name' => 'Reyes',
                'spouse_surname' => 'Santos',
                'spouse_ext_name' => null,
                'highest_education' => 'Elementary',
                'religion' => 'Roman Catholic',
                'id_type' => 'Barangay ID',
                'id_number' => '456789123',
                'is_icc_ip' => false,
                'icc_ip_name' => null,
                'is_pwd' => false,
                'is_4ps_beneficiary' => true,
                'association_1' => 'Farming Association Beta',
                'association_2' => null,
                'association_3' => null,
                'livelihood_type' => 'Farmer',
                'qr_code_hash' => hash('sha256', 'farmer_pedro_003'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Farmer 4: Rosa Mercado
            [
                'id' => '44444444-4444-4444-4444-444444444444',
                'rsbsa_no' => '2026-004-FARMER',
                'transaction_code' => 'TRX-004',
                'photo_path' => null,
                'surname' => 'Mercado',
                'first_name' => 'Rosa',
                'middle_name' => 'Tolentino',
                'ext_name' => null,
                'no_middle_name' => false,
                'no_ext_name' => true,
                'sex' => 'Female',
                'permanent_house_no' => '321',
                'permanent_street' => 'Bonifacio Lane',
                'permanent_brgy' => 'Lalakay',
                'permanent_city' => 'Sta. Rosa',
                'permanent_province' => 'Laguna',
                'permanent_region' => 'CALABARZON',
                'provincial_house_no' => null,
                'provincial_street' => null,
                'provincial_brgy' => null,
                'provincial_city' => null,
                'provincial_province' => null,
                'provincial_region' => null,
                'birthdate' => Carbon::create(1990, 11, 8),
                'place_of_birth_city' => 'Sta. Rosa',
                'place_of_birth_province' => 'Laguna',
                'mobile_number' => '09123456789',
                'is_mobile_owner' => true,
                'mobile_owner_first_name' => null,
                'mobile_owner_middle_name' => null,
                'mobile_owner_surname' => null,
                'mobile_owner_ext_name' => null,
                'mothers_maiden_first_name' => 'Teresita',
                'mothers_maiden_middle_name' => null,
                'mothers_maiden_surname' => 'Tolentino',
                'mothers_maiden_ext_name' => null,
                'civil_status' => 'Widow/er',
                'spouse_first_name' => null,
                'spouse_middle_name' => null,
                'spouse_surname' => null,
                'spouse_ext_name' => null,
                'highest_education' => 'Senior High School K-12',
                'religion' => 'Iglesia ni Cristo',
                'id_type' => 'National ID',
                'id_number' => '741852963',
                'is_icc_ip' => false,
                'icc_ip_name' => null,
                'is_pwd' => false,
                'is_4ps_beneficiary' => true,
                'association_1' => 'Organic Farmers Collective',
                'association_2' => null,
                'association_3' => null,
                'livelihood_type' => 'Farmer',
                'qr_code_hash' => hash('sha256', 'farmer_rosa_004'),
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Farmer 5: Antonio Reyes
            [
                'id' => '55555555-5555-5555-5555-555555555555',
                'rsbsa_no' => '2026-005-FARMER',
                'transaction_code' => 'TRX-005',
                'photo_path' => null,
                'surname' => 'Reyes',
                'first_name' => 'Antonio',
                'middle_name' => 'Castillo',
                'ext_name' => 'Sr.',
                'no_middle_name' => false,
                'no_ext_name' => false,
                'sex' => 'Male',
                'permanent_house_no' => '654',
                'permanent_street' => 'Magsaysay Drive',
                'permanent_brgy' => 'Karangalan',
                'permanent_city' => 'Cavite',
                'permanent_province' => 'Cavite',
                'permanent_region' => 'CALABARZON',
                'provincial_house_no' => null,
                'provincial_street' => null,
                'provincial_brgy' => null,
                'provincial_city' => null,
                'provincial_province' => null,
                'provincial_region' => null,
                'birthdate' => Carbon::create(1955, 2, 28),
                'place_of_birth_city' => 'Cavite',
                'place_of_birth_province' => 'Cavite',
                'mobile_number' => '09156789012',
                'is_mobile_owner' => true,
                'mobile_owner_first_name' => null,
                'mobile_owner_middle_name' => null,
                'mobile_owner_surname' => null,
                'mobile_owner_ext_name' => null,
                'mothers_maiden_first_name' => 'Victoria',
                'mothers_maiden_middle_name' => 'Castillo',
                'mothers_maiden_surname' => 'Castillo',
                'mothers_maiden_ext_name' => null,
                'civil_status' => 'Married',
                'spouse_first_name' => 'Erlinda',
                'spouse_middle_name' => 'Pascual',
                'spouse_surname' => 'Reyes',
                'spouse_ext_name' => null,
                'highest_education' => 'Junior High School K-12',
                'religion' => 'Roman Catholic',
                'id_type' => 'Senior Citizen ID',
                'id_number' => '369258147',
                'is_icc_ip' => false,
                'icc_ip_name' => null,
                'is_pwd' => false,
                'is_4ps_beneficiary' => false,
                'association_1' => 'Rice Farmers Association',
                'association_2' => null,
                'association_3' => null,
                'livelihood_type' => 'Farmer',
                'qr_code_hash' => hash('sha256', 'farmer_antonio_005'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
