<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class FarmPlotSeeder extends Seeder
{
    /**
     * Seed farm plots for testing farmers.
     */
    public function run(): void
    {
        // Disable foreign key constraints temporarily
        Schema::disableForeignKeyConstraints();

        DB::table('farm_plots')->truncate();

        Schema::enableForeignKeyConstraints();

        DB::table('farm_plots')->insert([
            // Plots for Farmer 1: Juan Dela Cruz (2 plots, total 2.5 ha)
            [
                'id' => '11111111-aaaa-aaaa-aaaa-111111111111',
                'farmer_id' => '11111111-1111-1111-1111-111111111111',
                'location_brgy' => 'Poblacion',
                'location_city' => 'Santa Rosa',
                'location_province' => 'Laguna',
                'latitude' => '14.3596',
                'longitude' => '121.0202',
                'total_parcel_area_ha' => 2.5,
                'is_ancestral_domain' => false,
                'is_agrarian_reform_beneficiary' => false,
                'ownership_type' => 'Owned',
                'land_owner_first_name' => 'Juan',
                'land_owner_surname' => 'Dela Cruz',
                'land_owner_ext_name' => null,
                'proof_of_ownership_document' => 'Title',
                'commodity' => 'Rice',
                'size_ha' => 1.5,
                'no_of_heads_or_trees' => null,
                'farm_type' => 'Wetland',
                'is_organic' => false,
                'cropping_schedule' => 'Wet Season',
                'rotational_tiller_full_name' => null,
                'remarks' => 'Main rice field',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '11111111-bbbb-bbbb-bbbb-111111111111',
                'farmer_id' => '11111111-1111-1111-1111-111111111111',
                'location_brgy' => 'Poblacion',
                'location_city' => 'Santa Rosa',
                'location_province' => 'Laguna',
                'latitude' => '14.3600',
                'longitude' => '121.0210',
                'total_parcel_area_ha' => 1.0,
                'is_ancestral_domain' => false,
                'is_agrarian_reform_beneficiary' => false,
                'ownership_type' => 'Owned',
                'land_owner_first_name' => 'Juan',
                'land_owner_surname' => 'Dela Cruz',
                'land_owner_ext_name' => null,
                'proof_of_ownership_document' => 'Title',
                'commodity' => 'Corn',
                'size_ha' => 1.0,
                'no_of_heads_or_trees' => null,
                'farm_type' => 'Upland',
                'is_organic' => false,
                'cropping_schedule' => 'Dry Season',
                'rotational_tiller_full_name' => null,
                'remarks' => 'Secondary corn plot',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            // Plots for Farmer 2: Maria Garcia (1 plot, 2.0 ha)
            [
                'id' => '22222222-aaaa-aaaa-aaaa-222222222222',
                'farmer_id' => '22222222-2222-2222-2222-222222222222',
                'location_brgy' => 'Niog',
                'location_city' => 'Pasig',
                'location_province' => 'Metro Manila',
                'latitude' => '14.5635',
                'longitude' => '121.5826',
                'total_parcel_area_ha' => 2.0,
                'is_ancestral_domain' => false,
                'is_agrarian_reform_beneficiary' => false,
                'ownership_type' => 'Owned',
                'land_owner_first_name' => 'Maria',
                'land_owner_surname' => 'Garcia',
                'land_owner_ext_name' => null,
                'proof_of_ownership_document' => 'Title',
                'commodity' => 'Vegetables',
                'size_ha' => 2.0,
                'no_of_heads_or_trees' => null,
                'farm_type' => 'Vegetable Garden',
                'is_organic' => true,
                'cropping_schedule' => 'Year-Round',
                'rotational_tiller_full_name' => null,
                'remarks' => 'Organic vegetable farm',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            // Plots for Farmer 3: Pedro Santos Jr. (1 plot, 1.5 ha)
            [
                'id' => '33333333-aaaa-aaaa-aaaa-333333333333',
                'farmer_id' => '33333333-3333-3333-3333-333333333333',
                'location_brgy' => 'San Isidro',
                'location_city' => 'Cabuyao',
                'location_province' => 'Laguna',
                'latitude' => '14.4220',
                'longitude' => '121.0250',
                'total_parcel_area_ha' => 1.5,
                'is_ancestral_domain' => false,
                'is_agrarian_reform_beneficiary' => true,
                'ownership_type' => 'ARB Land',
                'land_owner_first_name' => 'Government',
                'land_owner_surname' => 'ARB Program',
                'land_owner_ext_name' => null,
                'proof_of_ownership_document' => 'ARB Certificate',
                'commodity' => 'Rice',
                'size_ha' => 1.5,
                'no_of_heads_or_trees' => null,
                'farm_type' => 'Wetland',
                'is_organic' => false,
                'cropping_schedule' => 'Wet Season',
                'rotational_tiller_full_name' => null,
                'remarks' => 'Agrarian Reform Beneficiary plot',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            // Plots for Farmer 4: Rosa Mercado (1 plot, 1.0 ha)
            [
                'id' => '44444444-aaaa-aaaa-aaaa-444444444444',
                'farmer_id' => '44444444-4444-4444-4444-444444444444',
                'location_brgy' => 'Talipapa',
                'location_city' => 'Quezon City',
                'location_province' => 'Metro Manila',
                'latitude' => '14.6760',
                'longitude' => '121.0437',
                'total_parcel_area_ha' => 1.0,
                'is_ancestral_domain' => false,
                'is_agrarian_reform_beneficiary' => false,
                'ownership_type' => 'Leased',
                'land_owner_first_name' => 'Maria',
                'land_owner_surname' => 'Gonzales',
                'land_owner_ext_name' => null,
                'proof_of_ownership_document' => 'Lease Agreement',
                'commodity' => 'Organic Rice',
                'size_ha' => 1.0,
                'no_of_heads_or_trees' => null,
                'farm_type' => 'Wetland',
                'is_organic' => true,
                'cropping_schedule' => 'Wet Season',
                'rotational_tiller_full_name' => null,
                'remarks' => 'Leased organic farm',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

            // Plots for Farmer 5: Antonio Reyes Sr. (2 plots, total 3.0 ha)
            [
                'id' => '55555555-aaaa-aaaa-aaaa-555555555555',
                'farmer_id' => '55555555-5555-5555-5555-555555555555',
                'location_brgy' => 'Mahintay',
                'location_city' => 'Cabuyao',
                'location_province' => 'Laguna',
                'latitude' => '14.4340',
                'longitude' => '121.0180',
                'total_parcel_area_ha' => 2.0,
                'is_ancestral_domain' => false,
                'is_agrarian_reform_beneficiary' => false,
                'ownership_type' => 'Owned',
                'land_owner_first_name' => 'Antonio',
                'land_owner_surname' => 'Reyes',
                'land_owner_ext_name' => 'Sr.',
                'proof_of_ownership_document' => 'Title',
                'commodity' => 'Rice',
                'size_ha' => 2.0,
                'no_of_heads_or_trees' => null,
                'farm_type' => 'Wetland',
                'is_organic' => false,
                'cropping_schedule' => 'Wet Season',
                'rotational_tiller_full_name' => null,
                'remarks' => 'Senior farmer main rice field',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '55555555-bbbb-bbbb-bbbb-555555555555',
                'farmer_id' => '55555555-5555-5555-5555-555555555555',
                'location_brgy' => 'Mahintay',
                'location_city' => 'Cabuyao',
                'location_province' => 'Laguna',
                'latitude' => '14.4350',
                'longitude' => '121.0190',
                'total_parcel_area_ha' => 1.0,
                'is_ancestral_domain' => false,
                'is_agrarian_reform_beneficiary' => false,
                'ownership_type' => 'Owned',
                'land_owner_first_name' => 'Antonio',
                'land_owner_surname' => 'Reyes',
                'land_owner_ext_name' => 'Sr.',
                'proof_of_ownership_document' => 'Title',
                'commodity' => 'Corn',
                'size_ha' => 1.0,
                'no_of_heads_or_trees' => null,
                'farm_type' => 'Upland',
                'is_organic' => false,
                'cropping_schedule' => 'Dry Season',
                'rotational_tiller_full_name' => null,
                'remarks' => 'Secondary corn field',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
