<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

/**
 * Farm plots for the 15 Echague, Isabela farmers.
 *
 * Coordinates are authentic barangay-level positions within Echague, Isabela
 * (municipality center approx 16.7167 °N, 121.6833 °E).
 *
 * Commodities: Rice (wetland), Corn, Tobacco, Vegetables — typical of Isabela.
 */
class FarmPlotSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('farm_plots')->truncate();
        Schema::enableForeignKeyConstraints();

        $rows = [

            // ── Farmer 1: Eduardo Corpuz (San Fabian) ─────────────────────────────
            [
                'id'                            => 'b1000001-0000-0000-0000-000000000001',
                'farmer_id'                     => 'a1000001-0000-0000-0000-000000000001',
                'location_brgy'                 => 'San Fabian',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6842',
                'longitude'                     => '121.6715',
                'georef_id'                     => 'GPX-ECH-BAN-0001',
                'total_parcel_area_ha'          => 2.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Eduardo',
                'land_owner_surname'            => 'Corpuz',
                'land_owner_ext_name'           => 'Sr.',
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Rice',
                'size_ha'                       => 2.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Irrigated',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Irrigated lowland rice – San Fabian canal system',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],
            [
                'id'                            => 'b1000002-0000-0000-0000-000000000002',
                'farmer_id'                     => 'a1000001-0000-0000-0000-000000000001',
                'location_brgy'                 => 'San Fabian',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6860',
                'longitude'                     => '121.6730',
                'total_parcel_area_ha'          => 1.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Eduardo',
                'land_owner_surname'            => 'Corpuz',
                'land_owner_ext_name'           => 'Sr.',
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Corn',
                'size_ha'                       => 1.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Dry Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Upland corn plot',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 2: Marilyn Tumibay (San Fabian) ────────────────────────────
            [
                'id'                            => 'b1000003-0000-0000-0000-000000000003',
                'farmer_id'                     => 'a1000002-0000-0000-0000-000000000002',
                'location_brgy'                 => 'San Fabian',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6831',
                'longitude'                     => '121.6696',
                'total_parcel_area_ha'          => 1.5,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> true,
                'ownership_type'                => 'Others',
                'land_owner_first_name'         => 'Government',
                'land_owner_surname'            => 'CARP Program',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'ARB Certificate',
                'commodity'                     => 'Rice',
                'size_ha'                       => 1.5,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Lowland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'CARP beneficiary plot, San Fabian',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 3: Renato Caguioa (Garit Norte) ────────────────────────
            [
                'id'                            => 'b1000004-0000-0000-0000-000000000004',
                'farmer_id'                     => 'a1000003-0000-0000-0000-000000000003',
                'location_brgy'                 => 'Garit Norte',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6918',
                'longitude'                     => '121.6572',
                'georef_id'                     => 'GPX-ECH-GAN-0004',
                'total_parcel_area_ha'          => 2.5,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Renato',
                'land_owner_surname'            => 'Caguioa',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Corn',
                'size_ha'                       => 2.5,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Main corn field – Garit Norte upland',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 4: Teresita Palma (Garit Norte) ────────────────────────
            [
                'id'                            => 'b1000005-0000-0000-0000-000000000005',
                'farmer_id'                     => 'a1000004-0000-0000-0000-000000000004',
                'location_brgy'                 => 'Garit Norte',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6895',
                'longitude'                     => '121.6551',
                'total_parcel_area_ha'          => 1.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> true,
                'ownership_type'                => 'Others',
                'land_owner_first_name'         => 'Government',
                'land_owner_surname'            => 'CARP Program',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'ARB Certificate',
                'commodity'                     => 'Rice',
                'size_ha'                       => 1.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Irrigated',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Senior citizen ARB rice plot',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 5: Artemio Baquiran (Fugu) ─────────────────────────────
            [
                'id'                            => 'b1000006-0000-0000-0000-000000000006',
                'farmer_id'                     => 'a1000005-0000-0000-0000-000000000005',
                'location_brgy'                 => 'Fugu',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6625',
                'longitude'                     => '121.6804',
                'total_parcel_area_ha'          => 3.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Artemio',
                'land_owner_surname'            => 'Baquiran',
                'land_owner_ext_name'           => 'Jr.',
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Rice',
                'size_ha'                       => 3.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Irrigated',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Low-lying irrigated rice near Fugu River',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],
            [
                'id'                            => 'b1000007-0000-0000-0000-000000000007',
                'farmer_id'                     => 'a1000005-0000-0000-0000-000000000005',
                'location_brgy'                 => 'Fugu',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6641',
                'longitude'                     => '121.6821',
                'total_parcel_area_ha'          => 1.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Lessee',
                'land_owner_first_name'         => 'Julio',
                'land_owner_surname'            => 'Baquiran',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Lease Agreement',
                'commodity'                     => 'Tobacco',
                'size_ha'                       => 1.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Dry Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Leased tobacco plot',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 6: Felicito Talosig (Soyung (Poblacion)) ───────────────────────────
            [
                'id'                            => 'b1000008-0000-0000-0000-000000000008',
                'farmer_id'                     => 'a1000006-0000-0000-0000-000000000006',
                'location_brgy'                 => 'Soyung (Poblacion)',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7134',
                'longitude'                     => '121.6768',
                'total_parcel_area_ha'          => 2.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Felicito',
                'land_owner_surname'            => 'Talosig',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Rice',
                'size_ha'                       => 2.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Irrigated',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Irrigated rice – Soyung (Poblacion) lateral canal',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 7: Gloria Ferrer (Soyung (Poblacion)) ──────────────────────────────
            [
                'id'                            => 'b1000009-0000-0000-0000-000000000009',
                'farmer_id'                     => 'a1000007-0000-0000-0000-000000000007',
                'location_brgy'                 => 'Soyung (Poblacion)',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7118',
                'longitude'                     => '121.6784',
                'total_parcel_area_ha'          => 1.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Lessee',
                'land_owner_first_name'         => 'Pedro',
                'land_owner_surname'            => 'Talosig',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Lease Agreement',
                'commodity'                     => 'Vegetables',
                'size_ha'                       => 1.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Urban/Peri-Urban',
                'is_organic'                    => true,
                'cropping_schedule'             => 'Year-Round',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Organic vegetable garden – Soyung (Poblacion)',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 8: Rogelio Buenaobra (Mabbayad) ────────────────────────
            [
                'id'                            => 'b1000010-0000-0000-0000-000000000010',
                'farmer_id'                     => 'a1000008-0000-0000-0000-000000000008',
                'location_brgy'                 => 'Mabbayad',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7258',
                'longitude'                     => '121.6541',
                'total_parcel_area_ha'          => 2.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Rogelio',
                'land_owner_surname'            => 'Buenaobra',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Tobacco',
                'size_ha'                       => 2.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Dry Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Virginia tobacco – Mabbayad upland',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],
            [
                'id'                            => 'b1000011-0000-0000-0000-000000000011',
                'farmer_id'                     => 'a1000008-0000-0000-0000-000000000008',
                'location_brgy'                 => 'Mabbayad',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7271',
                'longitude'                     => '121.6518',
                'total_parcel_area_ha'          => 1.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Rogelio',
                'land_owner_surname'            => 'Buenaobra',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Rice',
                'size_ha'                       => 1.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Irrigated',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Secondary rice plot',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 9: Danilo Turingan (Magleticia) ──────────────────────────
            [
                'id'                            => 'b1000012-0000-0000-0000-000000000012',
                'farmer_id'                     => 'a1000009-0000-0000-0000-000000000009',
                'location_brgy'                 => 'Magleticia',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7308',
                'longitude'                     => '121.7022',
                'georef_id'                     => 'GPX-ECH-MAC-0012',
                'total_parcel_area_ha'          => 3.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Danilo',
                'land_owner_surname'            => 'Turingan',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Rice',
                'size_ha'                       => 3.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Irrigated',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Large irrigated rice tract – Magleticia',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 10: Vilma Batoon (Magleticia) ────────────────────────────
            [
                'id'                            => 'b1000013-0000-0000-0000-000000000013',
                'farmer_id'                     => 'a1000010-0000-0000-0000-000000000010',
                'location_brgy'                 => 'Magleticia',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7330',
                'longitude'                     => '121.7041',
                'total_parcel_area_ha'          => 1.5,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Vilma',
                'land_owner_surname'            => 'Batoon',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Corn',
                'size_ha'                       => 1.5,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Senior citizen upland corn field',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 11: Jaime Manantan (Pag-asa) ────────────────────────────
            [
                'id'                            => 'b1000014-0000-0000-0000-000000000014',
                'farmer_id'                     => 'a1000011-0000-0000-0000-000000000011',
                'location_brgy'                 => 'Pag-asa',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7001',
                'longitude'                     => '121.6438',
                'total_parcel_area_ha'          => 2.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Jaime',
                'land_owner_surname'            => 'Manantan',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Corn',
                'size_ha'                       => 2.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Upland corn – Pag-asa hillside',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 12: Nimrod Carpio (San Antonio Ugad) ─────────────────────────
            [
                'id'                            => 'b1000015-0000-0000-0000-000000000015',
                'farmer_id'                     => 'a1000012-0000-0000-0000-000000000012',
                'location_brgy'                 => 'San Antonio Ugad',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7319',
                'longitude'                     => '121.6475',
                'total_parcel_area_ha'          => 2.5,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Nimrod',
                'land_owner_surname'            => 'Carpio',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Rice',
                'size_ha'                       => 2.5,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Irrigated',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Irrigated lowland – San Antonio Ugad',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],
            [
                'id'                            => 'b1000016-0000-0000-0000-000000000016',
                'farmer_id'                     => 'a1000012-0000-0000-0000-000000000012',
                'location_brgy'                 => 'San Antonio Ugad',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7335',
                'longitude'                     => '121.6490',
                'total_parcel_area_ha'          => 1.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Lessee',
                'land_owner_first_name'         => 'Emilio',
                'land_owner_surname'            => 'Carpio',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Lease Agreement',
                'commodity'                     => 'Tobacco',
                'size_ha'                       => 1.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Dry Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Leased tobacco patch',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 13: Elvira Aguinaldo (Rumang-ay) ───────────────────────
            [
                'id'                            => 'b1000017-0000-0000-0000-000000000017',
                'farmer_id'                     => 'a1000013-0000-0000-0000-000000000013',
                'location_brgy'                 => 'Rumang-ay',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7831',
                'longitude'                     => '121.6962',
                'total_parcel_area_ha'          => 1.5,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Elvira',
                'land_owner_surname'            => 'Aguinaldo',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Corn',
                'size_ha'                       => 1.5,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Remote upland corn – Rumang-ay',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 14: Roberto Cabanatan (Narra) ──────────────────────
            [
                'id'                            => 'b1000018-0000-0000-0000-000000000018',
                'farmer_id'                     => 'a1000014-0000-0000-0000-000000000014',
                'location_brgy'                 => 'Narra',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.7758',
                'longitude'                     => '121.7072',
                'total_parcel_area_ha'          => 2.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Roberto',
                'land_owner_surname'            => 'Cabanatan',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Corn',
                'size_ha'                       => 2.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Upland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Narra upland corn',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

            // ── Farmer 15: Priscilla Tallungan (Gumbauan) ─────────────────────
            [
                'id'                            => 'b1000019-0000-0000-0000-000000000019',
                'farmer_id'                     => 'a1000015-0000-0000-0000-000000000015',
                'location_brgy'                 => 'Gumbauan',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6683',
                'longitude'                     => '121.6631',
                'total_parcel_area_ha'          => 1.0,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Registered Owner',
                'land_owner_first_name'         => 'Priscilla',
                'land_owner_surname'            => 'Tallungan',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Title',
                'commodity'                     => 'Vegetables',
                'size_ha'                       => 1.0,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Urban/Peri-Urban',
                'is_organic'                    => true,
                'cropping_schedule'             => 'Year-Round',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Organic vegetable plot – Gumbauan',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],
            [
                'id'                            => 'b1000020-0000-0000-0000-000000000020',
                'farmer_id'                     => 'a1000015-0000-0000-0000-000000000015',
                'location_brgy'                 => 'Gumbauan',
                'location_city'                 => 'Echague',
                'location_province'             => 'Isabela',
                'latitude'                      => '16.6698',
                'longitude'                     => '121.6648',
                'total_parcel_area_ha'          => 0.5,
                'is_ancestral_domain'           => false,
                'is_agrarian_reform_beneficiary'=> false,
                'ownership_type'                => 'Lessee',
                'land_owner_first_name'         => 'Augusto',
                'land_owner_surname'            => 'Tallungan',
                'land_owner_ext_name'           => null,
                'proof_of_ownership_document'   => 'Lease Agreement',
                'commodity'                     => 'Rice',
                'size_ha'                       => 0.5,
                'no_of_heads_or_trees'          => null,
                'farm_type'                     => 'Rainfed Lowland',
                'is_organic'                    => false,
                'cropping_schedule'             => 'Wet Season',
                'rotational_tiller_full_name'   => null,
                'remarks'                       => 'Small leased rice plot',
                'created_at'                    => now(),
                'updated_at'                    => now(),
                'deleted_at'                    => null,
            ],

        ];

        // Normalize optional RSBSA columns so every row shares the same key set
        // (required for a single bulk insert).
        foreach ($rows as &$row) {
            $row['georef_id'] = $row['georef_id'] ?? null;
            $row['land_owner_rsbsa_no'] = $row['land_owner_rsbsa_no'] ?? null;
        }
        unset($row);

        DB::table('farm_plots')->insert($rows);
    }
}
